### ISSUE TITLE
Getting compilation error :compileJava failed

### ISSUE THREAD

**Issue by harshit98** [yacy/yacy_grid_crawler#2]
I was working on #1. While building docker image I get compilation error: 

![screenshot from 2017-07-25 20-18-58](https://user-images.githubusercontent.com/22245418/28579277-cf9c1a5a-7179-11e7-828c-ace82676a6bb.png)

Even manual build is giving compilation error:

![20394666_1585718951478161_668160340_o](https://user-images.githubusercontent.com/22245418/28579298-e175cd5c-7179-11e7-91c5-4fb99eafeaab.png)

@Orbiter Please look. :)

**Comment by Orbiter** [comment]
This looks like the submodule is missing. The submodule contains the complete MCP which also holds the package or.json.

The README of this project explains how to get the submodule in the Installation section:
You must clone the project with
```
git clone --recursive https://github.com/yacy/yacy_grid_crawler.git
```

If you have not done this, you can fix it afterwards with
```
git submodule foreach git pull origin master
```

**Comment by Orbiter** [comment]
that solved it
